travis draft

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -3,6 +3,8 @@ version: '2'
 
 vars:
   CMD_LIST_PACKAGES: go list ./... | grep -v /vendor/
+  GOOS:
+    sh: uname | tr '[:upper:]' '[:lower:]'
   VERSION_DEP: "v0.5.0"
 
 tasks:
@@ -21,7 +23,7 @@ tasks:
         echo "Going to compile to ${COMPILE_PATH}" &&
         export BINARY_PATH=${COMPILE_PATH};
         fi;
-        go build -race -ldflags "-extldflags '-static'" -o ${BINARY_PATH}
+        go build -race -ldflags "-s -w -extldflags '-static'" -o ${BINARY_PATH}-{{ .GOOS }}
     sources:
       - "**/*.go"
     generates:
@@ -35,11 +37,11 @@ tasks:
     desc: "Quick tests such as fmt and vet"
     cmds:
       - dep check
-#      - if [ ! -z $(gofmt -e -l **/*.go) ]; then
-#        echo "Files with formatting errors:";
-#        gofmt -e -l **/*.go;
-#        exit 1;
-#        fi
+      - if [ ! -z $(gofmt -e -l **/*.go) ]; then
+        echo "Files with formatting errors:";
+        gofmt -e -l **/*.go;
+        exit 1;
+        fi
       - go vet $({{ .CMD_LIST_PACKAGES }})
     deps: [build]
 
@@ -61,3 +63,5 @@ tasks:
   require-dep:
     cmds:
       - curl https://raw.githubusercontent.com/golang/dep/{{ .VERSION_DEP }}/install.sh | sh
+    status:
+      - test -f "$(command -v dep)"
